// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJ09RuhoNmDKk6rO8ni7uzLmcS3NLF5Q0',
    appId: '1:630825608761:web:11e5073e5ad651e0fccfe8',
    messagingSenderId: '630825608761',
    projectId: 'flutterproject-d428e',
    authDomain: 'flutterproject-d428e.firebaseapp.com',
    databaseURL: 'https://flutterproject-d428e-default-rtdb.firebaseio.com',
    storageBucket: 'flutterproject-d428e.appspot.com',
    measurementId: 'G-RG366NG66X',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJ09RuhoNmDKk6rO8ni7uzLmcS3NLF5Q0',
    appId: '1:630825608761:web:b040094f9da06b1dfccfe8',
    messagingSenderId: '630825608761',
    projectId: 'flutterproject-d428e',
    authDomain: 'flutterproject-d428e.firebaseapp.com',
    databaseURL: 'https://flutterproject-d428e-default-rtdb.firebaseio.com',
    storageBucket: 'flutterproject-d428e.appspot.com',
    measurementId: 'G-PVVSEZ2JTM',
  );
}
